image: node:lts

stages:
  - test-coverage
  - sonarscan
  - build

cache:
  paths:
    - node_modules/

test-sdk:
  stage: test-coverage
  tags:
    - linux-docker
  script:
    - npm i && npm run test
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  artifacts:
    when: always
    expire_in: 1h
    paths:
      - coverage/

build-ui-sdk:
  stage: build
  tags:
    - linux-docker
  script:
    - npm i
    - npm run build
  artifacts:
    paths:
      - build/

sonarqube-check:
  stage: sonarscan
  tags:
      - linux-docker
  dependencies:
    - test-sdk
  image:
      name: sonarsource/sonar-scanner-cli:latest
  variables:
      # sonarqube requires full clone for commit history-enriched analysis reporting
      GIT_DEPTH: 0
      SONAR_PROJECT_BASE_DIR: "${CI_PROJECT_DIR}"
  script:
      - sonar-scanner -X -Dproject.settings=sonar-project.properties -Dsonar.qualitygate.wait=true
  allow_failure: true
  rules:
      - if: "$CI_PIPELINE_SOURCE == 'push'"  
      - if: "$CI_PIPELINE_SOURCE == 'merge_request_event'"  
      - if: '$CI_COMMIT_REF_NAME  == "master" '  
      - if: '$CI_COMMIT_REF_NAME  =~ /^release/'



