image: node:lts

stages:
  - test
  - build

test-sdk:
  stage: test
  tags:
    - linux-docker
  script:
    - npm i && npm run test

build-ui-sdk:
  stage: build
  tags:
    - linux-docker
  script:
    - npm i
    - npm run build
  artifacts:
    paths:
      - build
  


