image: node:lts

stages:
  - test-coverage
  - build

test-coverage:
  stage: test_coverage
  tags:
    - linux-docker
  script:
    - npm i && npm run test
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  artifacts:
    when: always
    expire_in: 1h
    paths:
      - coverage
      - src/*
  only:
    - develop
    - master

build-ui-sdk:
  stage: build
  tags:
    - linux-docker
  script:
    - npm i
    - npm run clean
    - npm run build
  artifacts:
    paths:
      - build
  


