export enum MESSAGE_TYPES {
  GET_CONFIGURATION = 'GetConfiguration',
  SET_CONFIGURATION = 'SetConfiguration'
}

export enum SUBSCRIPTION_EVENTS {
  MODEL_UPDATED = 'MODEL_UPDATED',
  AYX_APP_CONTEXT_UPDATED = 'AYX_APP_CONTEXT_UPDATED',
  INIT = 'INIT'
}
