name: Node.js CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install components dependencies
        working-directory: packages/components
        run: npm install --include=dev

      - name: Build components
        working-directory: packages/components
        run: npm run build:publish

      - name: Run component tests
        working-directory: packages/components
        run: npm run test